language: r

env:
  matrix:
    - TARGET=travis
    
apt_packages:
 - libxml2-dev

r_github_packages:
 - Rdatatable/data.table
 - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()' 
